name: Run VBS Script

on: [push]

jobs:
  run-vbs:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run VBS script as admin
      run: |
        echo Set objShell = CreateObject("Shell.Application") > temp.vbs
        echo objShell.ShellExecute "cmd.exe", "/c cscript %cd%\script.vbs", "", "runas", 1 >> temp.vbs
        cscript temp.vbs
