name: Run VBS Script

on: [push]

jobs:
  run-vbs:
    runs-on: self-hosted
    if: runner.labels.contains('DESKTOP-7NFAGLG')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run VBS script as admin
      run: |
        cmd.exe /c cscript %cd%\script.vbs runas 1
